# ...

development:
  adapter: postgresql
  encoding: unicode
  database: conscious_development
  pool: 5
  username:
  password:

# ...

test:
  adapter: postgresql
  encoding: unicode
  database: conscious_test
  pool: 5
  username:
  password:
